#!/usr/bin/env bash
# Rebuild the voxedge wheel from the sibling source repo and stage it into
# deploy/wheels/ for the Docker image builds.
#
# WHY THIS EXISTS
#   The product imports `voxedge`, a pure-Python library that lives in its own
#   repository at ../voxedge. Release images install an exact published PyPI
#   version. This helper builds a local wheel only for pre-publication device
#   qualification and records provenance beside it.
#
#   The wheel filename follows the version in voxedge/pyproject.toml. The
#   v0.9.1 release contract requires exactly 0.0.9a0; a mismatch fails before a
#   local qualification wheel is staged. The sidecar carries the exact source
#   revision and wheel digest.
#
# USAGE
#   scripts/build_voxedge_wheel.sh            # build from ../voxedge
#   VOXEDGE_SRC=/path/to/voxedge scripts/build_voxedge_wheel.sh
#
# deploy/wheels is intentionally gitignored. Never commit the generated wheel;
# publish the qualified version and pin it in server/requirements.txt instead.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VOXEDGE_SRC="${VOXEDGE_SRC:-$(cd "${REPO_ROOT}/../voxedge" && pwd)}"
WHEELS_DIR="${REPO_ROOT}/deploy/wheels"
EXPECTED_VERSION="${VOXEDGE_VERSION:-0.0.9a0}"

if [[ ! -f "${VOXEDGE_SRC}/pyproject.toml" ]]; then
  echo "ERROR: voxedge source not found at ${VOXEDGE_SRC}" >&2
  echo "       set VOXEDGE_SRC=/abs/path/to/voxedge" >&2
  exit 1
fi

echo "==> voxedge source: ${VOXEDGE_SRC}"
SRC_SHA="$(cd "${VOXEDGE_SRC}" && git rev-parse HEAD 2>/dev/null || echo unknown)"
SRC_DIRTY="clean"
if ! (cd "${VOXEDGE_SRC}" && git diff --quiet && git diff --cached --quiet) 2>/dev/null; then
  SRC_DIRTY="DIRTY (uncommitted changes — wheel will NOT be reproducible)"
fi
BUILD_DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

echo "==> building wheel (uv build --wheel)"
# Strip macOS cruft so it never lands in the published artifact (setuptools
# otherwise sweeps .DS_Store into the wheel as a data file).
find "${VOXEDGE_SRC}" -name .DS_Store -delete 2>/dev/null || true
rm -rf "${VOXEDGE_SRC}/dist" "${VOXEDGE_SRC}/build"
( cd "${VOXEDGE_SRC}" && uv build --wheel >/dev/null )

WHEEL_PATH="$(ls -t "${VOXEDGE_SRC}"/dist/voxedge-*-py3-none-any.whl | head -1)"
WHEEL_NAME="$(basename "${WHEEL_PATH}")"
EXPECTED_WHEEL_NAME="voxedge-${EXPECTED_VERSION}-py3-none-any.whl"
if [[ "${WHEEL_NAME}" != "${EXPECTED_WHEEL_NAME}" ]]; then
  echo "ERROR: expected ${EXPECTED_WHEEL_NAME}, found ${WHEEL_NAME}" >&2
  echo "       publish/qualify VoxEdge ${EXPECTED_VERSION}; do not stage an older wheel." >&2
  exit 1
fi
mkdir -p "${WHEELS_DIR}"

# Remove any prior voxedge wheel so a version bump never leaves two behind.
rm -f "${WHEELS_DIR}"/voxedge-*-py3-none-any.whl
cp "${WHEEL_PATH}" "${WHEELS_DIR}/${WHEEL_NAME}"

WHEEL_SHA256="$(shasum -a 256 "${WHEELS_DIR}/${WHEEL_NAME}" | awk '{print $1}')"

cat > "${WHEELS_DIR}/voxedge.BUILD.txt" <<EOF
# Provenance for ${WHEEL_NAME} — regenerated by scripts/build_voxedge_wheel.sh
wheel:        ${WHEEL_NAME}
wheel_sha256: ${WHEEL_SHA256}
source_repo:  voxedge (../voxedge)
source_sha:   ${SRC_SHA}
source_state: ${SRC_DIRTY}
built_at:     ${BUILD_DATE}
EOF

echo "==> staged ${WHEELS_DIR}/${WHEEL_NAME}"
echo "==> provenance ${WHEELS_DIR}/voxedge.BUILD.txt"
echo "    source_sha:   ${SRC_SHA}"
echo "    source_state: ${SRC_DIRTY}"
if [[ "${SRC_DIRTY}" != "clean" ]]; then
  echo "WARNING: voxedge source had uncommitted changes — commit them before deploy." >&2
fi
