#!/usr/bin/env bash
# Rebuild the voxedge wheel from the sibling source repo and stage it into
# deploy/wheels/ for the Docker image builds.
#
# WHY THIS EXISTS
#   The product (server/ + agent/) imports `voxedge`, a pure-Python library that
#   lives in its OWN repo at ../voxedge. The Docker images install it from a
#   wheel staged at deploy/wheels/voxedge-<ver>-py3-none-any.whl (see the
#   Dockerfile.* COPY lines). That wheel is a build artifact — it can drift from
#   ../voxedge source if rebuilt by hand and forgotten. This script makes the
#   rebuild one command AND records provenance (source git SHA + dirty flag +
#   build date) in a sidecar so you can always tell which voxedge a wheel holds.
#
#   The wheel FILENAME is intentionally version-stable (voxedge/pyproject.toml
#   pins 0.0.1a0) so the 8 Dockerfiles that COPY it never need editing. The
#   sidecar — not the filename — carries the "which build is this" signal.
#
# USAGE
#   scripts/build_voxedge_wheel.sh            # build from ../voxedge
#   VOXEDGE_SRC=/path/to/voxedge scripts/build_voxedge_wheel.sh
#
# After running, commit BOTH deploy/wheels/voxedge-*.whl and
# deploy/wheels/voxedge.BUILD.txt so the deployed artifact and its provenance
# travel together.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VOXEDGE_SRC="${VOXEDGE_SRC:-$(cd "${REPO_ROOT}/../voxedge" && pwd)}"
WHEELS_DIR="${REPO_ROOT}/deploy/wheels"

if [[ ! -f "${VOXEDGE_SRC}/pyproject.toml" ]]; then
  echo "ERROR: voxedge source not found at ${VOXEDGE_SRC}" >&2
  echo "       set VOXEDGE_SRC=/abs/path/to/voxedge" >&2
  exit 1
fi

echo "==> voxedge source: ${VOXEDGE_SRC}"
SRC_SHA="$(cd "${VOXEDGE_SRC}" && git rev-parse HEAD 2>/dev/null || echo unknown)"
SRC_DIRTY="clean"
if ! (cd "${VOXEDGE_SRC}" && git diff --quiet && git diff --cached --quiet) 2>/dev/null; then
  SRC_DIRTY="DIRTY (uncommitted changes — wheel will NOT be reproducible)"
fi
BUILD_DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

echo "==> building wheel (uv build --wheel)"
# Strip macOS cruft so it never lands in the published artifact (setuptools
# otherwise sweeps .DS_Store into the wheel as a data file).
find "${VOXEDGE_SRC}" -name .DS_Store -delete 2>/dev/null || true
rm -rf "${VOXEDGE_SRC}/dist" "${VOXEDGE_SRC}/build"
( cd "${VOXEDGE_SRC}" && uv build --wheel >/dev/null )

WHEEL_PATH="$(ls -t "${VOXEDGE_SRC}"/dist/voxedge-*-py3-none-any.whl | head -1)"
WHEEL_NAME="$(basename "${WHEEL_PATH}")"
mkdir -p "${WHEELS_DIR}"

# Remove any prior voxedge wheel so a version bump never leaves two behind.
rm -f "${WHEELS_DIR}"/voxedge-*-py3-none-any.whl
cp "${WHEEL_PATH}" "${WHEELS_DIR}/${WHEEL_NAME}"

WHEEL_SHA256="$(shasum -a 256 "${WHEELS_DIR}/${WHEEL_NAME}" | awk '{print $1}')"

cat > "${WHEELS_DIR}/voxedge.BUILD.txt" <<EOF
# Provenance for ${WHEEL_NAME} — regenerated by scripts/build_voxedge_wheel.sh
wheel:        ${WHEEL_NAME}
wheel_sha256: ${WHEEL_SHA256}
source_repo:  voxedge (../voxedge)
source_sha:   ${SRC_SHA}
source_state: ${SRC_DIRTY}
built_at:     ${BUILD_DATE}
EOF

echo "==> staged ${WHEELS_DIR}/${WHEEL_NAME}"
echo "==> provenance ${WHEELS_DIR}/voxedge.BUILD.txt"
echo "    source_sha:   ${SRC_SHA}"
echo "    source_state: ${SRC_DIRTY}"
if [[ "${SRC_DIRTY}" != "clean" ]]; then
  echo "WARNING: voxedge source had uncommitted changes — commit them before deploy." >&2
fi
