"""Real-machine injected voice-capture regression for the reBot arm config.

Unlike the other e2e tests (which use client_vad_backend="energy"), this suite
replicates the PRODUCTION reBot voice path — client_vad_backend="off" + the
energy gate — so it exercises the 2026-06-13 first-utterance fixes against the
LIVE SLV ASR (orin-nx:8621):
  * P0 energy-gate pre-roll (command onset survives the gate)
  * P1 reconnect_on_wake=false (first post-wake command not dropped)
  * P2 short wake-tone suppression

Scripted WAVs are injected through the real mic pump → real SLV ASR; we assert
on the ASR final text the server returns. macOS `say -v Tingting` fixtures are
generated by conftest / the cmd_*.wav generator. The fade-in variants press the
onset below the gate threshold to prove the pre-roll recovers it.

Run: pytest tests/e2e/test_rebot_voice_capture.py -v -s  (needs orin-nx live)
"""
from __future__ import annotations

import asyncio
import wave
from dataclasses import replace

import aiohttp
import numpy as np
import pytest

from .conftest import run_agent, WAV_DIR
from .fake_audio import ScriptedAudioIO

# reBot command corpus (macOS `say -v Tingting`; committed for non-macOS CI).
_REBOT_CMDS = [
    ("cmd_grab_box", "抓盒子"),
    ("cmd_grab_box_full", "把盒子抓起来"),
    ("cmd_put_back", "放回原位"),
    ("cmd_put_back_full", "把盒子放回原位"),
    ("cmd_wave", "挥手"),
    ("cmd_go_home", "回家"),
    ("cmd_search_box", "找一下盒子"),
]
# Fade-in variants: linearly ramp the first 300ms so the onset sits BELOW the
# energy-gate threshold — the only way to exercise the P0 pre-roll recovery
# (clean `say` output starts loud and never trips the gate-truncation bug).
_FADEIN = [("cmd_grab_box", 300), ("cmd_put_back_full", 300),
           ("cmd_en_drop_down", 200)]

# English commands (macOS `say -v Samantha`; committed for non-macOS CI). These
# exercise the FIRST-WORD-DROP regression on space-delimited speech: the Silero
# onset clip + the streaming worker's single-token hold both drop the leading
# verb ("drop it down" → "it down" / just "drop"), which the dispatcher preroll
# ring + the clipped-final offline rescue (voxedge 2026-06-15) must recover.
# (wav stem, full text, required substring after normalize()).
_REBOT_EN_CMDS = [
    ("cmd_en_drop_down", "drop it down", "drop"),
    ("cmd_en_please_drop_down", "please drop it down", "drop"),
]

# Natural-voice corpus synthesised on orin-nano (Qwen3 TRT TTS, 24kHz — the
# e2e loader auto-resamples to 16k). Committed WAVs; no `say` dependency. More
# natural onsets/homophones than `say -v Tingting`, so this is the production-
# representative ASR-quality probe. (wav stem, expected substring in the final).
_REBOT_TTS_CMDS = [
    ("tts_q_grab_box", "盒子"),
    ("tts_q_grab_box_full", "盒子"),
    ("tts_q_put_back", "放回"),
    ("tts_q_put_back_full", "放回"),
    ("tts_q_wave", "挥手"),
    ("tts_q_go_home", "回"),
    ("tts_q_search_box", "盒子"),
    ("tts_q_stop", "停"),
    ("tts_q_grab_cup", "杯子"),
]


def _ensure_rebot_wavs() -> None:
    WAV_DIR.mkdir(parents=True, exist_ok=True)
    for name, text in _REBOT_CMDS:
        out = WAV_DIR / f"{name}.wav"
        if out.exists() and out.stat().st_size > 0:
            continue
        raise FileNotFoundError(
            f"required E2E WAV fixture is missing: {out}; restore/commit it"
        )
    for name, text, _need in _REBOT_EN_CMDS:
        out = WAV_DIR / f"{name}.wav"
        if out.exists() and out.stat().st_size > 0:
            continue
        raise FileNotFoundError(
            f"required E2E WAV fixture is missing: {out}; restore/commit it"
        )
    for src, fade_ms in _FADEIN:
        out = WAV_DIR / f"{src}_fadein.wav"
        if out.exists() and out.stat().st_size > 0:
            continue
        with wave.open(str(WAV_DIR / f"{src}.wav"), "rb") as w:
            sr = w.getframerate()
            a = np.frombuffer(w.readframes(w.getnframes()), dtype=np.int16).astype(np.float32)
        ramp = np.linspace(0.0, 1.0, min(int(sr * fade_ms / 1000), len(a)))
        a[: len(ramp)] *= ramp
        with wave.open(str(out), "wb") as w:
            w.setnchannels(1)
            w.setsampwidth(2)
            w.setframerate(sr)
            w.writeframes(a.astype(np.int16).tobytes())


_ensure_rebot_wavs()


def _rebot_voice_config(base):
    """Production reBot voice parameters layered onto the e2e base config."""
    return replace(
        base,
        pipeline_mode="wake_word",
        wake_command_single_turn=False,
        client_vad_backend="off",        # server-VAD path → energy gate runs
        energy_gate_enabled=True,
        energy_gate_open_rms=0.020,
        energy_gate_close_rms=0.010,
        energy_gate_hangover_ms=300,
        mic_makeup_gain=3.0,
        gate_drive_eos=True,
        gate_eos_min_speech_ms=250,
        gate_eos_delay_ms=200,
        reconnect_on_wake=False,
        mic_drop_while_speaking=True,
        sleep_timeout_s=45.0,
        system_prompt="你是机械臂语音助手，简洁回应。",
    )


async def _wake(app, cfg) -> None:
    port = cfg.metadata["dashboard_port"]
    async with aiohttp.ClientSession() as s:
        async with s.post(f"http://127.0.0.1:{port}/api/control/wake") as r:
            assert r.status == 200


def _last_user_text(app) -> str:
    for msg in reversed(app.session.history or []):
        if msg.get("role") == "user":
            return str(msg.get("content") or "")
    return ""


def _normalize(text: str) -> str:
    """Lower-case + strip punctuation so substring checks ignore ASR casing /
    trailing periods ('Drop it down.' → 'drop it down')."""
    import re
    return re.sub(r"[^\w\s]", "", str(text or "")).lower().strip()


@pytest.mark.asyncio
async def test_grab_box_clean_onset(test_config):
    """Baseline: a clean (loud-onset) '抓盒子' is transcribed with the object
    word intact — confirms the gate path + live ASR work end to end."""
    cfg = _rebot_voice_config(test_config)
    audio = ScriptedAudioIO([(1500, WAV_DIR / "cmd_grab_box.wav")])
    async with run_agent(cfg, audio) as (app, probe):
        await _wake(app, cfg)
        await probe.wait_event("on_wake", timeout=5)
        await probe.wait_event("on_user_utterance", timeout=25)
        text = _last_user_text(app)
        print(f"\n[clean onset] ASR final = {text!r}")
        assert "盒子" in text, f"object word lost: {text!r}"


@pytest.mark.asyncio
async def test_grab_box_low_onset_preroll(test_config):
    """P0: a faded-in '抓盒子' whose onset sits BELOW the gate threshold. The
    pre-roll must replay the buffered onset so the ASR still hears the leading
    '抓', not just '盒子'."""
    cfg = _rebot_voice_config(test_config)
    audio = ScriptedAudioIO([(1500, WAV_DIR / "cmd_grab_box_fadein.wav")])
    async with run_agent(cfg, audio) as (app, probe):
        await _wake(app, cfg)
        await probe.wait_event("on_wake", timeout=5)
        await probe.wait_event("on_user_utterance", timeout=25)
        text = _last_user_text(app)
        print(f"\n[low onset + preroll] ASR final = {text!r}")
        # The onset survives if the leading verb '抓' is recovered. We assert
        # the object word at minimum and report the verb so a regression
        # (onset truncated to just '盒子') is visible.
        assert "盒子" in text, f"object word lost: {text!r}"
        assert "抓" in text, f"ONSET LOST — preroll did not recover '抓': {text!r}"


@pytest.mark.asyncio
async def test_command_immediately_after_wake(test_config):
    """P1: the FIRST command after wake must land. Inject the command only
    AFTER wake completes (runtime inject, not a fixed pre-wake script delay) so
    we test the real "wake then speak" order, not a capture-vs-wake race. With
    reconnect_on_wake=false the hot WS persists so the utterance isn't dropped
    in a reconnect window."""
    cfg = _rebot_voice_config(test_config)
    audio = ScriptedAudioIO([])  # nothing pre-wake
    async with run_agent(cfg, audio) as (app, probe):
        await _wake(app, cfg)
        await probe.wait_event("on_wake", timeout=5)
        # Past the wake-tone suppression (250ms) — the user's command proper.
        await asyncio.sleep(0.5)
        audio.inject(WAV_DIR / "cmd_grab_box.wav")
        await probe.wait_event("on_user_utterance", timeout=25)
        text = _last_user_text(app)
        print(f"\n[post-wake command] ASR final = {text!r}")
        assert "盒子" in text, f"first post-wake command lost/truncated: {text!r}"


@pytest.mark.asyncio
@pytest.mark.parametrize(
    "wav,must_contain",
    [
        ("cmd_put_back_full", "放回"),
        ("cmd_wave", "挥手"),
        ("cmd_go_home", "回"),
        ("cmd_search_box", "盒子"),
    ],
)
async def test_command_word_asr_accuracy(test_config, wav, must_contain):
    """Probe ASR accuracy of each demo command word — surfaces homophone /
    truncation issues per command (e.g. '挥手'→'灰手', '回家'→'回家了')."""
    cfg = _rebot_voice_config(test_config)
    audio = ScriptedAudioIO([(1200, WAV_DIR / f"{wav}.wav")])
    async with run_agent(cfg, audio) as (app, probe):
        await _wake(app, cfg)
        await probe.wait_event("on_wake", timeout=5)
        await probe.wait_event("on_user_utterance", timeout=25)
        text = _last_user_text(app)
        print(f"\n[asr {wav}] = {text!r}  (need {must_contain!r})")
        assert must_contain in text, f"{wav}: got {text!r}, missing {must_contain!r}"


@pytest.mark.asyncio
async def test_command_during_speaking_is_dropped(test_config):
    """Echo gate: with mic_drop_while_speaking=true a command spoken WHILE the
    agent is SPEAKING (playing its own TTS) must be dropped BEFORE reaching the
    SLV — otherwise the mic would transcribe the agent's own TTS echo into a
    false command. Barge-in during SPEAKING is intentionally OFF (no hardware-
    AEC echo verification yet), so this asserts the drop.

    We hold the agent in SPEAKING across the injection for a deterministic echo
    window — real replies are too short to reliably overlap, and (since the
    multi_utterance ASR fix, server 9b084a5) a command landing after the reply
    ends IS now transcribed, which is correct and covered by
    test_scenario_accuracy::after_action_idle. The pure mic-gate mechanism is
    also unit-tested in tests/test_bargein_mic_forward.py."""
    from ovs_agent.state import ConvState

    cfg = _rebot_voice_config(test_config)
    audio = ScriptedAudioIO([])
    async with run_agent(cfg, audio) as (app, probe):
        await _wake(app, cfg)
        await probe.wait_event("on_wake", timeout=5)
        await asyncio.sleep(0.6)  # clear the wake-tone suppression
        n_before = sum(1 for e in probe.events if e.get("event") == "on_user_utterance")
        # Hold SPEAKING across the injection (the echo-gate window).
        app._state = ConvState.SPEAKING
        audio.inject(WAV_DIR / "cmd_grab_box.wav")  # spoken "over" the agent's TTS
        await asyncio.sleep(4.0)
        app._state = ConvState.IDLE
        n_after = sum(1 for e in probe.events if e.get("event") == "on_user_utterance")
        print(f"\n[echo-gate] utterances before={n_before} after={n_after}")
        assert n_after == n_before, (
            "a command spoken while SPEAKING must be dropped by the echo gate "
            "(mic_drop_while_speaking) — it reached the SLV and was transcribed. "
            "If barge-in-during-TTS was intentionally enabled (AEC verified), "
            "update this test."
        )


@pytest.mark.parametrize("tail_ms,react_ms", [(200, 120), (120, 120), (60, 120), (200, 350)])
async def test_done_tone_tail_vs_onset(test_config, tail_ms, react_ms):
    """P0/② TAIL SWEEP: after a completion tone the mic is suppressed for
    `tail_ms` (grasp_plugin done-tone). If the user reacts in `react_ms` (< tail)
    the command onset lands INSIDE the suppression window and is lost (suppress
    drops audio AND clears pre-roll, so the gate pre-roll can't recover it).
    Sweep to find the tail that doesn't eat a fast follow-up command's onset.
    Reports ASR per (tail, react) so the production tail can be set on data."""
    import time as _t

    cfg = _rebot_voice_config(test_config)
    audio = ScriptedAudioIO([])
    async with run_agent(cfg, audio) as (app, probe):
        await _wake(app, cfg)
        await probe.wait_event("on_wake", timeout=5)
        await asyncio.sleep(0.6)  # clear the wake-tone suppression first
        # Simulate the done-tone's mic suppression window.
        app._local_output_mic_suppress_until = _t.monotonic() + tail_ms / 1000.0
        await asyncio.sleep(react_ms / 1000.0)  # user reaction time after the beep
        audio.inject(WAV_DIR / "cmd_grab_box.wav")
        try:
            await probe.wait_event("on_user_utterance", timeout=25)
        except AssertionError:
            print(f"\n[tail={tail_ms} react={react_ms}] ASR = <none>")
            raise
        text = _last_user_text(app)
        lost = "抓" not in text
        print(f"\n[tail={tail_ms} react={react_ms}] ASR = {text!r}  onset_lost={lost}")
        # Document, don't hard-fail on onset loss — this is a measurement sweep.
        assert "盒子" in text, f"whole command lost: {text!r}"


# Known-bad corpus fixtures. xfail(strict=False) so the suite stays green but
# the issue stays visible (auto-flips to PASS if the fixture is regenerated).
#   tts_q_wave: the orin-nano Qwen3-TTS rendering of 挥手 (huī shǒu) is mis-
#   synthesised with a tone the ASR hears as 回首 (huí shǒu). This is a
#   TTS-FIXTURE artifact, NOT an ASR weakness — BOTH paraformer_trt AND qwen3
#   (trt_edgellm) transcribe this WAV as 回首, while the macOS `say` 挥手
#   (cmd_wave.wav, test_command_word_asr_accuracy) is recognised correctly.
#   To fix: regenerate tts_q_wave with clearer synthesis.
_ASR_KNOWN_BAD = {"tts_q_wave"}


@pytest.mark.asyncio
@pytest.mark.parametrize(
    "wav,must_contain",
    [
        pytest.param(
            w, c,
            marks=pytest.mark.xfail(
                reason="TTS fixture artifact: Qwen3-TTS 挥手 renders as 回首 "
                "(both ASR engines agree); regenerate the WAV to fix",
                strict=False,
            ),
        )
        if w in _ASR_KNOWN_BAD else (w, c)
        for w, c in _REBOT_TTS_CMDS
    ],
)
async def test_qwen_corpus_asr_accuracy(test_config, wav, must_contain):
    """Natural-voice (Qwen3 TTS) reBot command corpus through the live SLV ASR.
    Validates the committed orin-nano corpus end to end AND gives a production-
    representative ASR-quality regression — these onsets/homophones are closer
    to real mic input than the robotic `say -v Tingting` fixtures."""
    cfg = _rebot_voice_config(test_config)
    audio = ScriptedAudioIO([(1200, WAV_DIR / f"{wav}.wav")])
    async with run_agent(cfg, audio) as (app, probe):
        await _wake(app, cfg)
        await probe.wait_event("on_wake", timeout=5)
        await probe.wait_event("on_user_utterance", timeout=25)
        text = _last_user_text(app)
        print(f"\n[qwen asr {wav}] = {text!r}  (need {must_contain!r})")
        assert must_contain in text, f"{wav}: got {text!r}, missing {must_contain!r}"


# ── English first-word-drop regression (needs orin-nx live; code only) ─────────
# These exercise the 2026-06-15 voxedge fixes against the LIVE SLV ASR:
#   * dispatcher preroll ring  → the Silero-clipped onset reaches the stream
#   * clipped-final offline rescue → a single-token streaming final ("drop") on
#     a multi-word utterance is re-transcribed offline into the full command.
# The leading verb "drop" is the canary: if it's missing, the onset was lost.
# Mark needs-device — they only RUN on orin-nx:8621 (no-op on CI without it).


@pytest.mark.asyncio
async def test_en_drop_it_down_clean_onset(test_config):
    """First-word fix (clean onset): 'drop it down' must keep the leading verb
    'drop' — not collapse to 'it down'. Live SLV ASR via the engine path."""
    cfg = _rebot_voice_config(test_config)
    cfg = replace(
        cfg,
        slv_config={**cfg.slv_config, "asr_language": "en", "tts_language": "en"},
        system_prompt="You are a robot arm voice assistant. Reply briefly.",
    )
    audio = ScriptedAudioIO([(1500, WAV_DIR / "cmd_en_drop_down.wav")])
    async with run_agent(cfg, audio) as (app, probe):
        await _wake(app, cfg)
        await probe.wait_event("on_wake", timeout=5)
        await probe.wait_event("on_user_utterance", timeout=25)
        text = _normalize(_last_user_text(app))
        print(f"\n[en clean] ASR final = {text!r}")
        assert text, "empty/clipped final — no response (offline rescue should fire)"
        assert "drop" in text, f"FIRST WORD LOST — 'drop' missing: {text!r}"


@pytest.mark.asyncio
async def test_en_drop_it_down_low_onset_preroll(test_config):
    """First-word fix (faded onset): 'drop it down' with the first 200ms ramped
    below the gate threshold. The preroll ring must replay the onset so 'drop'
    survives; the clipped-final rescue covers a single-token streaming final."""
    cfg = _rebot_voice_config(test_config)
    cfg = replace(
        cfg,
        slv_config={**cfg.slv_config, "asr_language": "en", "tts_language": "en"},
        system_prompt="You are a robot arm voice assistant. Reply briefly.",
    )
    audio = ScriptedAudioIO([(1500, WAV_DIR / "cmd_en_drop_down_fadein.wav")])
    async with run_agent(cfg, audio) as (app, probe):
        await _wake(app, cfg)
        await probe.wait_event("on_wake", timeout=5)
        await probe.wait_event("on_user_utterance", timeout=25)
        text = _normalize(_last_user_text(app))
        print(f"\n[en low onset + preroll] ASR final = {text!r}")
        assert text, "empty/clipped final — no response (offline rescue should fire)"
        assert "drop" in text, f"ONSET LOST — preroll did not recover 'drop': {text!r}"


@pytest.mark.asyncio
async def test_en_please_drop_it_down_control(test_config):
    """Control: 'please drop it down' has a non-verb leading word ('please'), so
    even with the onset clipped the worker commits multiple tokens and 'drop'
    lands. This is the case that ALREADY worked — guards against a regression in
    the normal multi-token fast path (no offline rescue expected)."""
    cfg = _rebot_voice_config(test_config)
    cfg = replace(
        cfg,
        slv_config={**cfg.slv_config, "asr_language": "en", "tts_language": "en"},
        system_prompt="You are a robot arm voice assistant. Reply briefly.",
    )
    audio = ScriptedAudioIO([(1500, WAV_DIR / "cmd_en_please_drop_down.wav")])
    async with run_agent(cfg, audio) as (app, probe):
        await _wake(app, cfg)
        await probe.wait_event("on_wake", timeout=5)
        await probe.wait_event("on_user_utterance", timeout=25)
        text = _normalize(_last_user_text(app))
        print(f"\n[en control] ASR final = {text!r}")
        assert text, "empty final on the control case — unexpected"
        assert "drop" in text, f"control regressed — 'drop' missing: {text!r}"
